apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dnsovertls
  name: dnsovertls
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsovertls
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dnsovertls
    spec:
      containers:
      - image: bala2805/dns-tls:1.0
        name: dns-proxy
        ports:
        - containerPort: 12555
