apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dnsovertls
  name: dnsovertls
spec:
  ports:
  - port: 12555
    protocol: TCP
    targetPort: 12555
  selector:
    app: dnsovertls
  type: LoadBalancer
status:
  loadBalancer: {}
